/******************************************************************************/
/***          Generated by IBExpert 2011.02.18 15.06.2016 11:24:00          ***/
/******************************************************************************/

SET SQL DIALECT 3;

SET NAMES NONE;

SET CLIENTLIB 'D:\QtProgects\build-QontMan-Desktop_Qt_5_5_1_MinGW_32bit-Debug\debug\fbclient.dll';

CREATE DATABASE 'D:\QtProgects\build-QontMan-Desktop_Qt_5_5_1_MinGW_32bit-Debug\debug\DATA.FDB'
USER 'SYSDBA' PASSWORD 'masterkey'
PAGE_SIZE 16384
DEFAULT CHARACTER SET NONE;



/******************************************************************************/
/***                               Generators                               ***/
/******************************************************************************/

CREATE GENERATOR "GEN_contact_ID";
SET GENERATOR "GEN_contact_ID" TO 68;



SET TERM ^ ; 



/******************************************************************************/
/***                           Stored Procedures                            ***/
/******************************************************************************/

CREATE PROCEDURE "SP_GEN_contact_ID"
RETURNS (
    ID INTEGER)
AS
BEGIN
  SUSPEND;
END^






SET TERM ; ^



/******************************************************************************/
/***                                 Tables                                 ***/
/******************************************************************************/



CREATE TABLE "contact" (
    ID           INTEGER NOT NULL,
    TIP          INTEGER,
    "TIMESTAMP"  VARCHAR(30) CHARACTER SET WIN1251,
    TEL          VARCHAR(58) CHARACTER SET WIN1251,
    FAX          VARCHAR(30) CHARACTER SET WIN1251,
    ADRES        VARCHAR(105) CHARACTER SET WIN1251,
    EMAIL        VARCHAR(31) CHARACTER SET WIN1251,
    HTTP         VARCHAR(32) CHARACTER SET WIN1251,
    UPLEVEL      INTEGER,
    NOTES        VARCHAR(100) CHARACTER SET WIN1251
);

CREATE TABLE "firm" (
    "id"         INTEGER NOT NULL,
    "sobstv"     VARCHAR(30) CHARACTER SET WIN1251,
    "name"       VARCHAR(32) CHARACTER SET WIN1251,
    "shortname"  VARCHAR(32) CHARACTER SET WIN1251
);

CREATE TABLE IMAGE (
    ID     INTEGER NOT NULL,
    IMAGE  BLOB SUB_TYPE 0 SEGMENT SIZE 80
);

CREATE TABLE "man" (
    "id"          INTEGER NOT NULL,
    "name"        VARCHAR(30) CHARACTER SET WIN1251,
    "surname"     VARCHAR(30) CHARACTER SET WIN1251,
    "patronymic"  VARCHAR(30) CHARACTER SET WIN1251,
    "shortname"   VARCHAR(34) CHARACTER SET WIN1251
);



/******************************************************************************/
/***                              Primary Keys                              ***/
/******************************************************************************/

ALTER TABLE "contact" ADD CONSTRAINT PK_CONTACT PRIMARY KEY (ID);
ALTER TABLE "firm" ADD CONSTRAINT PK_FIRM PRIMARY KEY ("id");
ALTER TABLE "man" ADD CONSTRAINT PK_MAN PRIMARY KEY ("id");


/******************************************************************************/
/***                                Triggers                                ***/
/******************************************************************************/


SET TERM ^ ;



/******************************************************************************/
/***                          Triggers for tables                           ***/
/******************************************************************************/



/* Trigger: "contact_BI" */
CREATE TRIGGER "contact_BI" FOR "contact"
ACTIVE BEFORE INSERT POSITION 0
as
begin
  if (new.id is null) then
    new.id = gen_id("GEN_contact_ID",1);
end
^

SET TERM ; ^



/******************************************************************************/
/***                           Stored Procedures                            ***/
/******************************************************************************/


SET TERM ^ ;

ALTER PROCEDURE "SP_GEN_contact_ID"
RETURNS (
    ID INTEGER)
AS
begin
  id = gen_id("GEN_contact_ID", 1);
  suspend;
end^



SET TERM ; ^
